(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(LaTeX-command "latex")
 '(TeX-PDF-mode t)
 '(TeX-electric-sub-and-superscript t)
 '(auth-source-save-behavior nil)
 '(bibtex-help-message t)
  '(c-default-style
     '((c-mode . "linux")
	(java-mode . "java")
	(awk-mode . "awk")
	(other . "gnu")))
  '(c-mode-common-hook
     '((lambda nil
	 (add-hook 'before-save-hook 'delete-trailing-whitespace t t))))
 '(calendar-date-style 'european)
 '(calendar-week-start-day 1)
 '(case-fold-search t)
 '(column-number-mode t)
 '(comment-auto-fill-only-comments nil)
 '(comment-column 50)
 '(comment-empty-lines ''eol)
 '(comment-multi-line t)
 '(compilation-auto-jump-to-first-error t)
 '(compilation-message-face 'default)
 '(compilation-scroll-output 'first-error)
 '(compilation-window-height 15)
 '(coq-prog-args '("-emacs-U"))
 '(css-tab-mode 'indent)
 '(current-language-environment "UTF-8")
 '(custom-enabled-themes '(sanityinc-tomorrow-night))
 '(custom-file "~/.emacs.d/custom.el")
  '(custom-safe-themes
     '("628278136f88aa1a151bb2d6c8a86bf2b7631fbea5f0f76cba2a0079cd910f7d" "1b8d67b43ff1723960eb5e0cba512a2c7a2ad544ddb2533a90101fd1852b426e" "82d2cac368ccdec2fcc7573f24c3f79654b78bf133096f9b40c20d97ec1d8016" "0598c6a29e13e7112cfbc2f523e31927ab7dce56ebb2016b567e1eff6dc1fd4f" "06f0b439b62164c6f8f84fdda32b62fb50b6d00e8b01c2208e55543a6337433a" "bb08c73af94ee74453c90422485b29e5643b73b05e8de029a6909af6a3fb3f58" "2809bcb77ad21312897b541134981282dc455ccd7c14d74cc333b6e549b824f3" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" default))
 '(default-input-method "TeX")
 '(default-major-mode 'text-mode t)
 '(desktop-base-file-name "emacs.desktop")
 '(desktop-file-name-format 'absolute)
 '(desktop-path '("."))
 '(desktop-save 'if-exists)
 '(desktop-save-mode t)
 '(display-time-24hr-format t)
 '(display-time-mode t)
 '(ediff-window-setup-function 'ediff-setup-windows-plain)
 '(electric-indent-mode t)
 '(electric-layout-mode nil)
 '(european-calendar-style t)
 '(fill-nobreak-predicate '(fill-french-nobreak-p))
 '(footnote-spaced-footnotes nil)
 '(fringe-mode '(nil . 0) nil (fringe))
 '(git-show-unknown nil)
 '(git-show-uptodate t)
 '(global-auto-revert-mode t)
 '(global-font-lock-mode t nil (font-lock))
 '(global-hl-line-mode t)
 '(inhibit-startup-screen t)
 '(ispell-local-dictionary "en_GB-ize-w_accents")
 '(ispell-program-name "aspell")
 '(js-indent-level 2)
 '(js2-strict-missing-semi-warning nil)
 '(kill-whole-line t)
 '(line-move-visual nil)
 '(magit-diff-use-overlays nil)
 '(magit-use-overlays nil)
 '(menu-bar-mode nil)
 '(mouse-wheel-mode t)
 '(mouse-yank-at-point t)
 '(org-agenda-files '("~/org/org.org") t)
  '(org-modules
     '(org-bbdb org-bibtex org-docview org-gnus org-info org-jsinfo org-habit org-irc org-w3m org-git-link))
  '(projectile-globally-ignored-directories
     '(".idea" ".eunit" ".git" ".hg" ".fslckout" ".bzr" "_darcs" ".tox" ".svn"))
 '(prolog-program-name "pl")
 '(proof-electric-terminator-enable t)
 '(proof-prog-name "/usr/bin/ssrcoq")
 '(proof-shell-unicode t)
 '(proof-splash-enable nil)
 '(proof-toolbar-enable nil)
 '(require-final-newline t)
  '(safe-local-variable-values
     '((eval add-hook 'before-save-hook 'delete-trailing-whitespace nil t)
	(eval add-hook 'write-contents-functions 'delete-trailing-whitespace)
	(eval ignore-errors "Write-contents-functions is a buffer-local alternative to before-save-hook"
	  (add-hook 'write-contents-functions
	    (lambda nil
	      (delete-trailing-whitespace
		(point-min)
		(point-max))
	      nil)))
	(coq-prog-args "-emacs-U" "-impredicative-set")))
  '(same-window-regexps
     '("\\*rsh-[^-]*\\*\\(\\|<[0-9]*>\\)" "\\*telnet-.*\\*\\(\\|<[0-9]+>\\)" "^\\*rlogin-.*\\*\\(\\|<[0-9]+>\\)" "\\*info\\*\\(\\|<[0-9]+>\\)" "\\*gud-.*\\*\\(\\|<[0-9]+>\\)" "\\`\\*Customiz.*\\*\\'"))
 '(save-interprogram-paste-before-kill t)
 '(scroll-bar-mode nil)
 '(send-mail-function 'smtpmail-send-it)
 '(sentence-end-double-space nil)
 '(show-paren-mode t)
 '(straight-use-package-by-default t)
  '(text-mode-hook
     '(turn-on-auto-fill table-recognize text-mode-hook-identify))
 '(tool-bar-mode nil)
 '(transient-mark-mode t)
 '(typescript-auto-indent-flag nil)
 '(typescript-indent-level 2)
 '(user-full-name "Mathieu Boespflug")
 '(user-mail-address "mboes@tweag.net")
 '(visible-bell nil)
 '(woman-use-own-frame nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:height 140 :family "Iosevka"))))
 '(font-lock-function-name-face ((t (:height 1.0))))
 '(markup-complex-replacement-face ((t (:inherit markup-meta-face :background "purple3" :foreground "plum1" :box (:line-width 2 :style released-button) :height 0.7))))
 '(markup-meta-face ((t (:stipple nil :foreground "gray40" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown"))))
 '(markup-meta-hide-face ((t (:inherit markup-meta-face :foreground "gray40"))))
 '(markup-replacement-face ((t (:foreground "plum1"))))
 '(markup-secondary-text-face ((t (:inherit markup-gen-face :foreground "firebrick"))))
 '(markup-title-0-face ((t (:inherit markup-gen-face))))
 '(markup-title-1-face ((t (:inherit org-level-1))))
 '(markup-title-2-face ((t (:inherit org-level-2))))
 '(markup-title-3-face ((t (:inherit org-level-3))))
 '(markup-title-4-face ((t (:inherit org-level-4))))
 '(markup-title-5-face ((t (:inherit org-level-5))))
 '(markup-typewriter-face ((t (:inherit markup-gen-face)))))
